Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20240819082323_create_active_storage_tables.active_storage.rb, db/schema.rb
Remember to run 
`bundle install`
`rails db:migrate`
=> Added cloudinary & active storage

app/models/event.rb, app/models/order.rb, app/models/order_product.rb, app/models/product.rb, db/migrate/20240819082259_create_products.rb, db/migrate/20240819082658_create_events.rb, db/migrate/20240819082956_create_orders.rb, db/migrate/20240819083244_create_order_products.rb, db/migrate/20240819083532_add_shop_name_to_users.rb, db/schema.rb, test/models/event_test.rb, test/models/order_product_test.rb, test/models/order_test.rb, test/models/product_test.rb
- Add: Models and DB schema:  https://[kitt.lewagon.com/db/132081](https://kitt.lewagon.com/db/132081)
=> Add: Model setup

Gemfile.lock, db/schema.rb
=> Fixed DB schema

db/seeds.rb
=> Fixed the seeds

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/controllers/products_controller.rb, app/views/products/index.html.erb
Only grid for product and button for create
Please check
=> Lemonade Stand Products Index

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/views/products/index.html.erb, app/views/products/new.html.erb
changed colors, fixed index when no image, created create products"
=> Product create new branch

app/models/order.rb, db/migrate/20240820071917_make_event_id_optional_in_orders.rb, db/schema.rb, db/seeds.rb
- Add : order, event and order-product seeds
=> Add: Seeds

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_modal-bottom.scss, app/controllers/products_controller.rb, app/views/products/_new_form.erb, app/views/products/index.html.erb
Modal for create product - can be reused
=> Bottom modal

app/views/products/index.html.erb, app/views/shared/_navbar.html.erb
changed default image size loaded into index for laod and page performance
=> Changing index.picture size for page performance

app/controllers/orders_controller.rb, app/views/orders/_show_order.html.erb, app/views/orders/edit.html.erb, app/views/orders/show.html.erb
Made an order show page for final confirmation, checkout is now done on this page.
Discounts is also working with pre-determined percentages.
=> Add: Order Checkout Discount

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards.scss, app/javascript/controllers/quantity_controller.js, app/views/orders/_form.html.erb, app/views/orders/_show_order.html.erb
- Add: css style to cart
- Centering of edit page
=> Add: orders cart

app/assets/stylesheets/components/_modal-bottom.scss, app/views/products/_edit_form.html.erb, app/views/products/_edit_modal.html.erb, app/views/products/index.html.erb
Edit Button now calls the correct modal
=> Add edit modals

app/controllers/order_products_controller.rb, app/controllers/orders_controller.rb, app/javascript/controllers/cart_controller.js, app/javascript/controllers/quantity_controller.js, app/models/order.rb, app/models/user.rb, app/views/order_products/create.json.jbuilder, app/views/orders/_form.html.erb, app/views/orders/_show_order.html.erb, app/views/orders/edit.html.erb
- Add: Card +/- products connected to cart sum and quantity/names
- Removed unecessary method add_one_to_cart
=> Add: orders cart updated

app/controllers/pages_controller.rb, app/views/pages/home.html.erb, app/views/products/_edit_form.html.erb, app/views/products/_new_form.html.erb, app/views/shared/_navbar.html.erb
added Yen signs to new and edit form
=> Yen sign form

app/assets/stylesheets/components/_cards.scss
Doug suggested to try pixel first
=> Changed styling to pixel

app/javascript/controllers/discount_controller.js, app/views/orders/_show_order.html.erb, app/views/orders/edit.html.erb, app/views/orders/show.html.erb
When discount is selected, displays the new order total.
=> Add: Checkout discount

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards.scss, app/views/products/_product_cards.html.erb, app/views/products/index.html.erb
- Fixed position for plus button
- Refactor product cards to partial
- Remove gray border for edit button
- Added various media size (@media screen)
=> Fixed the plus-button and remove border for edit-button

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_modal-bottom.scss, app/assets/stylesheets/pages/_body.scss, app/assets/stylesheets/pages/_index.scss, app/views/orders/_cart_modal.html.erb, app/views/orders/edit.html.erb, app/views/products/_edit_modal.html.erb, app/views/products/_new_modal.html.erb
Change cart btn to hover with modal and improved animations on other modals
=> Checkout button sticky.hover

app/assets/stylesheets/components/_landing-background.scss, app/views/pages/home.html.erb
Added introduction to product on landing page
=> Added: Intro in landing page

db/seeds.rb
More products and events to have a random duration.
=> Edit Seeds for Products and Events

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards.scss, app/controllers/events_controller.rb, app/views/events/_events_cards.html.erb, app/views/events/index.html.erb, db/seeds.rb
orders automatically get assigned the event it upon seeding as well as after updating and creating
=> Events logic and modals

app/assets/stylesheets/components/_button.scss, app/controllers/products_controller.rb, app/views/orders/_form.html.erb, app/views/products/index.html.erb
=> Changed logic for @products in Product page and changed styling for create btn

app/assets/stylesheets/components/_button.scss, app/models/order.rb, app/models/user.rb, app/views/products/index.html.erb
=> Fixed the logic for product on orders index and small styling

app/views/events/index.html.erb
temporarily commented out all orders
=> Fix: index page for events

app/models/order.rb, app/models/user.rb, db/migrate/20240827095551_add_user_to_orders.rb, db/migrate/20240827100908_change_user_id_in_orders_to_not_null.rb, db/schema.rb, db/seeds.rb
clear your db first, than run migration, then seeds :)
=> added user id to orders and updated seeds

app/assets/stylesheets/components/_button.scss, app/views/orders/_form.html.erb, config/initializers/simple_form.rb, db/schema.rb
This PR addresses two issues:
1. Removes the asterisk (*) for required fields in Simple Form.
2. Updates the minus button to be more visually distinct.
- **Simple Form Initializer**: Updated `config/initializers/simple_form.rb` to remove the asterisk for required fields.
- **CSS**: Updated the `.btn-ghost` class to make the minus button more visually distinct.
- **HTML**: Updated the minus button to use a Font Awesome icon.
- Verified that the asterisk is no longer displayed for required fields.
- Ensured that the minus button is visually distinct and functions correctly.
=> Change: Edit page UI fix

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards.scss, app/controllers/orders_controller.rb, app/views/orders/_form.html.erb, app/views/orders/paypay.html.erb, app/views/orders/show.html.erb
**Description**:
This pull request moves the cart icon to be within the product image and fixes the issue where the cart icon disappears when the added amount is bigger than the inventory. The cart icon is now always displayed, and the quantity displayed is conditional based on the inventory status.
**Changes**:
- Move the cart icon to be within the product image.
- Always display the cart icon.
- Conditionally display the correct quantity based on the inventory.
=> Change: Cart icon fix

app/controllers/orders_controller.rb, app/views/orders/_order_list.html.erb
checkout button now remove zero qty order_products
=> Edit: Fix order show

app/assets/stylesheets/components/_cards.scss
=> fixed image border issue on events index

app/views/pages/home.html.erb
Moved to the bottom of landing page
=> Landing carousel

db/old_seeds.rb, db/seeds.rb
- moved the old seeds code to old_seeds.rb
- Seeds now set up user team@gmail.com's order history, event and products
=> Seeds Reset for Pitch

app/assets/stylesheets/components/_modal-bottom.scss, app/views/events/_edit_modal.html.erb, app/views/events/_new_modal.html.erb
**Modal Height Issue Resolved**
- Fixed Modal Height: Addressed the problem where the modals for creating and editing events didn't expand to the full required height.
- Custom Classes Implemented: Introduced custom classes specifically for these modals to ensure proper sizing without affecting other components.
=> Add event modal style improvements

app/views/layouts/application.html.erb
Remove twitter tags because its irrelevant now and it's also no longer twitter
=> Edit: remove twitter tags

app/controllers/orders_controller.rb, app/models/user.rb, app/views/products/_csv_form.html.erb
Added Required = true for CSV uploader
=> Fixed no CSV attachment for Products page

app/assets/stylesheets/components/_navbar.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/shared/_navbar.html.erb
First picture is on desktop view and second is on mobile
Also ask for shop name input on user registration
=> Edit: Login page

app/assets/stylesheets/components/_button.scss, app/controllers/products_controller.rb, app/views/products/_product_cards.html.erb
Added a delete btn to the products index page. 
Feel free to disagree with the positioning, or if you'd rather have the delete function somewhere else.
=> Product delete btn

app/views/layouts/application.html.erb
Added Google Tag to the head. (Minor change)
=> implemented gtag in head on application.html
